services:
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tests_base
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - qa-solar-internal

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    volumes:
      - ./apps/backend/:/app/apps/backend
      - ./node_modules:/app/node_modules
      - ./apps/backend/node_modules:/app/apps/backend/node_modules
    tty: true
    stdin_open: true
    command: ["yarn", "dev"]
    expose:
      - 3001
    ports:
      - "3001:3001"
    environment:
      - HOST=${HOST:-0.0.0.0}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - API_URL=${API_URL}
    depends_on:
      - postgres
    networks:
      - qa-solar-internal

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    volumes:
      - ./apps/frontend/:/app/apps/frontend
      - ./node_modules:/app/node_modules
      - ./apps/frontend/node_modules:/app/apps/frontend/node_modules
    tty: true
    stdin_open: true
    command: ["yarn", "dev", "--host", "0.0.0.0"]
    expose:
      - 8181
    ports:
      - "8181:8181"
    networks:
      - qa-solar-internal

volumes:
  postgres_data:

networks:
  qa-solar-internal:
