on:
  workflow_dispatch:

name: Setup Backend and Frontend
description: Configura o backend e frontend
runs:
  using: composite
  steps:
    - name: Iniciar backend
      run: |
        cd backend
        yarn prisma migrate dev
        yarn prisma:seed
        nohup yarn api > ../logs/backend.log 2>&1 &
      env:
        DATABASE_URL: ${{ vars.DATABASE_URL }}

    - name: Configurar e iniciar frontend
      run: |
        cd frontend
        nohup yarn serve > ../logs/frontend.log 2>&1 &
