name: Testes QA-Solar

on:
  push:
    branches:
      - main
      - feat/adiciona-ci-cd-no-projeto
  pull_request:
    branches:
      - main
      - feat/adiciona-ci-cd-no-projeto

jobs:
  setup-servers:
    name: Iniciar servidores Frontend e Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar e iniciar backend
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: |
          cd backend
          yarn install
          yarn api &

      - name: Configurar e iniciar frontend
        run: |
          cd frontend
          yarn install
          yarn serve &

      - name: Verificar disponibilidade do backend
        run: |
          curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:3001 || exit 1

      - name: Verificar disponibilidade do frontend
        run: |
          curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:8181 || exit 1

  cypress-tests:
    name: Executar testes Cypress
    runs-on: ubuntu-latest
    needs: setup-servers
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependências
        run: |
          cd test/cypress
          yarn install

      - name: Run Tests
        id: cypress
        uses: cypress-io/github-action@v6
        with:
          config-file: ./cypress.config.js
          browser: chrome
          wait-on: "http://localhost:3001"
          spec: test/cypress/tests/e2e/specs/*.cy.ts

  playwright-tests:
    name: Executar testes Playwright
    runs-on: ubuntu-latest
    needs: setup-servers
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependências
        run: |
          cd test/playwright
          yarn install

      - name: Executar testes Playwright
        run: |
          cd test/playwright
          yarn play:run

      - name: Upload de testes falhados
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  robot-tests:
    name: Executar testes Robot Framework
    runs-on: ubuntu-latest
    needs: setup-servers
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Instala as dependencias do Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb libxi6 libgconf-2-4
    
      - name: Cria ambiente virtual do Python
        run: python3.10 -m venv venv

      - name: Instalar dependências
        run: |
          cd test/robot
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Executar testes Robot Framework
        run: |
          cd test/robot
          source venv/bin/activate
          make test-all
